language: node_js
node_js:
- lts/*
before_script:
- npm run build
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: JdpMZPSODF0iDn0PfIe/TK3Vo5f64BT0s8HAvAymS9EECFURVjQRwxXUMwfPI21lWDTw7kCw91th48ZUz2ugktz11CI5JlgfW3cb+3y4b1JeJbn/vwLvDNxzdgteabi8CjWh5jnLuiEFqGIAxC3FeEE5AtvVzRnDbjk8fhupyYg=
  on:
    tags: true
    repo: noflo/noflo-tween
